### ISSUE TITLE
Could NOT find OgmaNeo

### ISSUE THREAD

**Issue by aktersnurra** [ogmacorp/PyOgmaNeo2#1]
Hi,

I am trying to install PyOgmaNeo2 on ubuntu 18.04 but I am running into to the following error message:

python3 setup.py install --user
running install
running build_ext
creating /home/aktersnurra/Documents/Packages/PyOgmaNeo2/build
creating /home/aktersnurra/Documents/Packages/PyOgmaNeo2/build/temp.linux-x86_64-3.6
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_BUILD_TYPE not set, setting it to Debug
-- Build type: Debug
Python target version: 3
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OgmaNeo (missing: OGMANEO_LIBRARY OGMANEO_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindOgmaNeo.cmake:36 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:34 (find_package)

NB: yes, I use the -DBUILD_SHARED_LIBS=ON flag when building the OgmaNeo2. I also tried linking the paths via my .bashrc file.

Cheers,

Gustaf

**Comment by 222464** [comment]
Hi,

Does changing line 21 in CMake/FindOgmaNeo.cmake from:

`FIND_PATH(OGMANEO_INCLUDE_DIR ogmaneo/neo/Hierarchy.h)`

To:

`FIND_PATH(OGMANEO_INCLUDE_DIR ogmaneo/Hierarchy.h)`

Work?

**Comment by aktersnurra** [comment]
Unfortunately it did not work. :(

**Comment by 222464** [comment]
Just checking: Did you run `sudo make install` on OgmaNeo? Is the library actually there (should be in /usr/lib or similar)? Also, try setting it to release mode (with -DCMAKE_BUILD_TYPE=Release)

**Comment by aktersnurra** [comment]
No, I did not use `sudo make install`, however it did not change anything when I tried it  I'm afraid. The lib and include directory is installed to `../OgmaNeo2/install/`.

**Comment by aktersnurra** [comment]
Ok, I have the solution to the problem now! :D Your pointer to "should be in.." together with the error message made me suspect that it looked for the headers and lib under the `/usr/` directory. 

So the solution to my problem is:

While installing OgmaNeo2 I had to change `cmake -DCMAKE_INSTALL_PREFIX=../install .. etc` to `cmake -DCMAKE_INSTALL_PREFIX=/usr .. -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release`

Thanks for the help!

**Comment by 222464** [comment]
> Hmm, it should default to `/usr/local`, but it seems it installed to the current directory instead. Try running CMake again with `-DCMAKE_INSTALL_PREFIX="/usr"` or `"/usr/local"` followed by `sudo make install`. It should print out the path it installed to when you do that.
> 
> If you want to use the current directory for the install instead, you can manually set OGMANEO_INCLUDE_DIR and OGMANEO_LIBRARY to the include directory and library file you want.

EDIT: Nevermind, you beat me to it haha!

**Comment by aktersnurra** [comment]
> Hmm, it should default to `/usr/local`, but it seems it installed to the current directory instead. Try running CMake again with `-DCMAKE_INSTALL_PREFIX="/usr"` or `"/usr/local"` followed by `sudo make install`. It should print out the path it installed to when you do that.
> 
> If you want to use the current directory for the install instead, you can manually set OGMANEO_INCLUDE_DIR and OGMANEO_LIBRARY to the include directory and library file you want.

Yeah, just figured it out before you posted as you can see. Again, thank you for your help. Looking forward to using the algorithm!

**Comment by 222464** [comment]
The instructions are incorrect then - I will remove the install prefix stated in the README.md

Thanks - hope you find the library helpful!
