### ISSUE TITLE
Error MSB4006

### ISSUE THREAD

**Issue by liquidnode** [ogmacorp/PyOgmaNeo2#3]
Got a "Error MSB4006: There is a circular dependency in the target dependency graph involving target "ResolveProjectReferences"" when compiling on Windows after the latest changes to CMakeLists.txt. An easy fix was to revert the changes on CMakeLists.txt.

**Comment by 222464** [comment]
Thanks for the report, I am going to try to reproduce it on my Windows partition.

**Comment by 222464** [comment]
I think I fixed it, try the latest.

It seems that for some reason the newer version of CMake on Windows is NOT case sensitive? Not sure, but changing the name PyOgmaNeo to PyOgmaNeoCpp in the CMakeLists fixes this.
